version: '3.8'

services:
  orchestrator:
    build: .
    container_name: orchestrator
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    command: ["mpiexec", "--allow-run-as-root", "--mca", "routed", "direct", "--mca", "btl_tcp_if_include", "eth0", "--hostfile", "/app/hostfile", "-n", "5", "python3", "/app/scripts/orchestrator.py"]
    networks:
      - mpi_network

  node-1:
    build: .
    container_name: node-1
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    command: ["mpiexec", "--allow-run-as-root", "--mca", "routed", "direct", "--mca", "btl_tcp_if_include", "eth0", "--hostfile", "/app/hostfile", "-n", "5", "python3", "/app/scripts/node_script.py"]
    networks:
      - mpi_network

  node-2:
    build: .
    container_name: node-2
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    command: ["mpiexec", "--allow-run-as-root", "--mca", "routed", "direct", "--mca", "btl_tcp_if_include", "eth0", "--hostfile", "/app/hostfile", "-n", "5", "python3", "/app/scripts/node_script.py"]
    networks:
      - mpi_network

  node-3:
    build: .
    container_name: node-3
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    command: ["mpiexec", "--allow-run-as-root", "--mca", "routed", "direct", "--mca", "btl_tcp_if_include", "eth0", "--hostfile", "/app/hostfile", "-n", "5", "python3", "/app/scripts/node_script.py"]
    networks:
      - mpi_network

  node-4:
    build: .
    container_name: node-4
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    command: ["mpiexec", "--allow-run-as-root", "--mca", "routed", "direct", "--mca", "btl_tcp_if_include", "eth0", "--hostfile", "/app/hostfile", "-n", "5", "python3", "/app/scripts/node_script.py"]
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge
